### ISSUE TITLE
Content-Type

### ISSUE THREAD

**Issue by JoyceBabu** [maingi4/APIGatewayS3Proxy#1]
First of all, thank you for sharing the code. You have saved me several hours of research :)

But one issue I have noticed is that the fetched resources are returned as `application/json`, unless I specify the correct `Content-Type` header in my request.

As per http://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-s3.html#api-items-in-folder-as-s3-objects-in-bucket this can be solved by setting the `Content-Type` header in _Integration Response_ to `integration.response.header.Content-Type`.

It would also be easier if you can convert all the placeholders (like `<your bucket name>`, `<your acc id>` and `<your acc id>`)  into parameters and place them under the `custom` key.

**Comment by maingi4** [comment]
Thanks for report. I have fixed the content type issue as well as status codes which weren't passing along in case of 404's etc.

Couldnt get to the placeholder thing though.. is it possible for you to send a pull request for that?

**Comment by JoyceBabu** [comment]
I have created the pull request for grouping all the account related information under a single location.

FYI, adding `integration.response.header.Content-Type` makes it work with curl. But it is not sufficient to make the image files render in a desktop Browser. 

APIG does not correctly handle requests with multple content types in `Accept`  header. When there are multiple content-types, APIG expects the first content-type to match one of the binary file types mentioned in the configuration. Else the output will have the correct mime type, but the response body will be `base64` encoded.  I had to set `BinaryMediaTypes` to `*/*`  to make it render in Chrome.

**Comment by maingi4** [comment]
i get the correct content-type when I upload an image.. I don't think I understood the problem.

**Comment by JoyceBabu** [comment]
When `integration.response.header.Content-Type` is not set
```
curl https://bucket-domain/filename.gif
```

returns the file with content type `application/json`.

But you can force the correct content type by specifying it in the request.
```
curl https://bucket-domain/filename.gif -H 'Content-Type: image/gif'
```

When `integration.response.header.Content-Type` is set

```
curl https://bucket-domain/filename.gif
```
returns the file with the correct content-type, and the file will be in binary format. But if you open it in Google Chrome, it will send the correct header, but the file body will be base 64 encoded. This is a known issue with API Gateway.

**Comment by maingi4** [comment]
hi, if you upload the image and specify the content-type along with it... the solution saves the content type (and content disposition) with the object in S3 in "object metadata", after that once you retrieve it the content-type is correctly set after the fix that I had done on your first comment.

I am closing the issue, do reopen if you feel there is still an issue. Thanks for the pull request regarding organizing the variable names btw.
